{{- if .Values.webhook.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    {{- include "n8n.selectorLabels" (dict "context" . "role" "webhook") | nindent 4 }}
spec:
  replicas: {{ .Values.webhook.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" (dict "context" . "role" "webhook") | nindent 6 }}
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 0
      steps:
        - setWeight: 50
        - pause: { duration: 1m }
        - setWeight: 100
  template:
    metadata:
      labels:
        {{- include "n8n.labels" . | nindent 8 }}
        {{- include "n8n.selectorLabels" (dict "context" . "role" "webhook") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- include "n8n.podAnnotations" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.webhook.terminationGracePeriodSeconds }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: n8n
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["n8n", "webhook"]
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "n8n.configMapName" . }}
            - secretRef:
                name: {{ include "n8n.secretName" . }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: {{ .Values.webhook.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.webhook.probes.readiness.periodSeconds }}
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
{{- end }}
