{{- if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secrets
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_POSTGRESDB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  QUEUE_BULL_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | quote }}
  {{- if .Values.secrets.apiKey }}
  N8N_API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.backup.enabled }}
  N8N_BACKUP_PAR_URL: {{ .Values.backup.parUrl | quote }}
  {{- end }}
{{- end }}
